-- Grande Realtors current database schema.
-- Safe to run against a fresh database or an older partially initialized one.
-- This file is intended to be the primary schema reference going forward.
-- Historical files under db/migrations can be kept for audit/reference, but
-- the operational setup path should start here.

BEGIN;

-- Static lookup tables used across the app.
CREATE TABLE IF NOT EXISTS roles (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO roles (name)
VALUES ('user'), ('agent'), ('admin')
ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS property_types (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO property_types (name)
VALUES ('land'), ('house'), ('apartment')
ON CONFLICT DO NOTHING;

-- Core user table. The ALTER keeps older databases aligned with the current app.
CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id VARCHAR(255) UNIQUE,
  firstname VARCHAR(100) NOT NULL,
  lastname VARCHAR(100) NOT NULL,
  number VARCHAR(20),
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role_id INTEGER REFERENCES roles(id),
  citizenship_front VARCHAR(255),
  citizenship_back VARCHAR(255),
  approval_status VARCHAR(50) DEFAULT 'approved',
  approval_reason TEXT,
  approved_at TIMESTAMP WITHOUT TIME ZONE,
  rejected_at TIMESTAMP WITHOUT TIME ZONE,
  reviewed_by INTEGER REFERENCES users(id),
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS public_id VARCHAR(255),
  ADD COLUMN IF NOT EXISTS citizenship_front VARCHAR(255),
  ADD COLUMN IF NOT EXISTS citizenship_back VARCHAR(255),
  ADD COLUMN IF NOT EXISTS approval_status VARCHAR(50) DEFAULT 'approved',
  ADD COLUMN IF NOT EXISTS approval_reason TEXT,
  ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP WITHOUT TIME ZONE,
  ADD COLUMN IF NOT EXISTS rejected_at TIMESTAMP WITHOUT TIME ZONE,
  ADD COLUMN IF NOT EXISTS reviewed_by INTEGER REFERENCES users(id),
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();

ALTER TABLE users
  ALTER COLUMN approval_status SET DEFAULT 'approved';

UPDATE users
SET approval_status = COALESCE(approval_status, 'approved')
WHERE approval_status IS NULL;

UPDATE users
SET role_id = (SELECT id FROM roles WHERE name = 'user')
WHERE role_id IN (
  SELECT id FROM roles WHERE name IN ('buyer', 'seller')
);

DELETE FROM roles
WHERE name IN ('buyer', 'seller');

-- Property catalog.
CREATE TABLE IF NOT EXISTS properties (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id VARCHAR(255) UNIQUE,
  owner_id INTEGER NOT NULL REFERENCES users(id),
  property_type_id INTEGER NOT NULL REFERENCES property_types(id),
  location TEXT NOT NULL,
  description TEXT,
  price NUMERIC NOT NULL,
  listing_purpose VARCHAR(50) DEFAULT 'sale',
  listing_type VARCHAR(50),
  sale_status VARCHAR(50) DEFAULT 'available',
  listed_date TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

ALTER TABLE properties
  ADD COLUMN IF NOT EXISTS public_id VARCHAR(255),
  ADD COLUMN IF NOT EXISTS listing_purpose VARCHAR(50) DEFAULT 'sale',
  ADD COLUMN IF NOT EXISTS listing_type VARCHAR(50),
  ADD COLUMN IF NOT EXISTS sale_status VARCHAR(50) DEFAULT 'available',
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();

ALTER TABLE properties
  ALTER COLUMN listing_purpose SET DEFAULT 'sale',
  ALTER COLUMN sale_status SET DEFAULT 'available';

UPDATE properties
SET listing_purpose = COALESCE(listing_purpose, 'sale'),
    sale_status = COALESCE(sale_status, 'available')
WHERE listing_purpose IS NULL
   OR sale_status IS NULL;

CREATE TABLE IF NOT EXISTS lands (
  property_id INTEGER PRIMARY KEY REFERENCES properties(id) ON DELETE CASCADE,
  area NUMERIC,
  dimensions VARCHAR(255),
  road_type VARCHAR(100),
  road_access VARCHAR(100),
  property_face VARCHAR(100),
  map_link TEXT
);

CREATE TABLE IF NOT EXISTS houses (
  property_id INTEGER PRIMARY KEY REFERENCES properties(id) ON DELETE CASCADE,
  area NUMERIC,
  number_of_floors INTEGER,
  number_of_bedrooms INTEGER
);

CREATE TABLE IF NOT EXISTS property_images (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id INTEGER NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL,
  uploaded_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS property_verification_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id INTEGER NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  request_status VARCHAR(50) DEFAULT 'pending',
  verified_date TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS assigned_properties (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id INTEGER NOT NULL REFERENCES users(id),
  property_id INTEGER NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  assigned_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  UNIQUE (agent_id, property_id)
);

CREATE TABLE IF NOT EXISTS favorites (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id),
  property_id INTEGER NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  added_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  UNIQUE (user_id, property_id)
);

CREATE TABLE IF NOT EXISTS inquiries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id),
  agent_id INTEGER REFERENCES users(id),
  property_id INTEGER NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  message TEXT,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS inquiry_messages (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inquiry_id INTEGER NOT NULL REFERENCES inquiries(id) ON DELETE CASCADE,
  sender_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  recipient_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  message TEXT NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  read_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE INDEX IF NOT EXISTS inquiry_messages_inquiry_id_idx
  ON inquiry_messages(inquiry_id, created_at);

CREATE TABLE IF NOT EXISTS notifications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id),
  description TEXT,
  sent_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  is_read BOOLEAN DEFAULT FALSE
);

-- Auction and bidding workflow.
CREATE TABLE IF NOT EXISTS auctions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id INTEGER NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  start_time TIMESTAMP WITHOUT TIME ZONE,
  end_time TIMESTAMP WITHOUT TIME ZONE,
  starting_price NUMERIC NOT NULL,
  status VARCHAR(50) DEFAULT 'open',
  UNIQUE (property_id)
);

ALTER TABLE auctions
  ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'open';

CREATE TABLE IF NOT EXISTS bid_tickets (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auction_id INTEGER NOT NULL REFERENCES auctions(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  transaction_uuid VARCHAR(120) NOT NULL UNIQUE,
  transaction_code VARCHAR(120),
  amount NUMERIC NOT NULL,
  status VARCHAR(20) DEFAULT 'pending',
  agreement_text TEXT,
  agreement_accepted_at TIMESTAMP WITHOUT TIME ZONE,
  paid_at TIMESTAMP WITHOUT TIME ZONE,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  UNIQUE (auction_id, user_id)
);

CREATE TABLE IF NOT EXISTS bid_ticket_agreements (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auction_id INTEGER NOT NULL REFERENCES auctions(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  agreement_text TEXT NOT NULL,
  accepted_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  UNIQUE (auction_id, user_id)
);

ALTER TABLE bid_tickets
  ADD COLUMN IF NOT EXISTS transaction_code VARCHAR(120),
  ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS agreement_text TEXT,
  ADD COLUMN IF NOT EXISTS agreement_accepted_at TIMESTAMP WITHOUT TIME ZONE,
  ADD COLUMN IF NOT EXISTS paid_at TIMESTAMP WITHOUT TIME ZONE,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();

CREATE TABLE IF NOT EXISTS bids (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auction_id INTEGER NOT NULL REFERENCES auctions(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id),
  bid_amount NUMERIC NOT NULL,
  bid_time TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  status VARCHAR(20) DEFAULT 'pending',
  responded_at TIMESTAMP WITHOUT TIME ZONE,
  is_winner BOOLEAN DEFAULT FALSE
);

ALTER TABLE bids
  ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS responded_at TIMESTAMP WITHOUT TIME ZONE;

-- Closed-sale features.
CREATE TABLE IF NOT EXISTS transactions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id INTEGER NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  buyer_id INTEGER NOT NULL REFERENCES users(id),
  seller_id INTEGER NOT NULL REFERENCES users(id),
  handler_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  amount NUMERIC NOT NULL,
  payment_method VARCHAR(50),
  transaction_date TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

ALTER TABLE transactions
  ADD COLUMN IF NOT EXISTS handler_id INTEGER REFERENCES users(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS contracts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bid_id INTEGER REFERENCES bids(id) ON DELETE CASCADE,
  property_id INTEGER NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  buyer_id INTEGER NOT NULL REFERENCES users(id),
  seller_id INTEGER NOT NULL REFERENCES users(id),
  transaction_id INTEGER REFERENCES transactions(id) ON DELETE SET NULL,
  contract_text TEXT NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  UNIQUE (bid_id)
);

CREATE INDEX IF NOT EXISTS contracts_property_id_idx ON contracts(property_id);
CREATE UNIQUE INDEX IF NOT EXISTS contracts_transaction_id_idx
  ON contracts(transaction_id)
  WHERE transaction_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS sales_handler_rating (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id INTEGER NOT NULL REFERENCES users(id),
  rated_by INTEGER NOT NULL REFERENCES users(id),
  rating NUMERIC,
  review TEXT,
  rated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  UNIQUE (agent_id, rated_by)
);

CREATE TABLE IF NOT EXISTS seller_ratings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seller_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  transaction_id INTEGER NOT NULL REFERENCES transactions(id) ON DELETE CASCADE,
  rated_by INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  rating NUMERIC NOT NULL,
  review TEXT,
  rated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  UNIQUE (transaction_id, rated_by)
);

CREATE INDEX IF NOT EXISTS seller_ratings_seller_id_idx
  ON seller_ratings(seller_id);

CREATE TABLE IF NOT EXISTS ratings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  buyer_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  rated_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  property_id INTEGER NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  transaction_id INTEGER NOT NULL REFERENCES transactions(id) ON DELETE CASCADE,
  role_type VARCHAR(20) NOT NULL CHECK (role_type IN ('seller', 'handler')),
  stars INTEGER NOT NULL CHECK (stars BETWEEN 1 AND 5),
  review TEXT,
  is_hidden BOOLEAN NOT NULL DEFAULT FALSE,
  moderated_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  moderated_at TIMESTAMP WITHOUT TIME ZONE,
  moderation_reason TEXT,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  UNIQUE (transaction_id, buyer_id, role_type)
);

CREATE INDEX IF NOT EXISTS ratings_rated_user_role_idx
  ON ratings(rated_user_id, role_type);

CREATE INDEX IF NOT EXISTS ratings_transaction_idx
  ON ratings(transaction_id);

-- Search and auth support tables.
CREATE TABLE IF NOT EXISTS search_history (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id),
  search_query TEXT NOT NULL,
  searched_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS password_resets (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash VARCHAR(255) NOT NULL,
  expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  used_at TIMESTAMP WITHOUT TIME ZONE,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS password_resets_token_hash_idx
  ON password_resets(token_hash);

CREATE INDEX IF NOT EXISTS password_resets_user_id_idx
  ON password_resets(user_id);

CREATE TABLE IF NOT EXISTS refresh_tokens (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash VARCHAR(255) NOT NULL UNIQUE,
  expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  revoked_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE INDEX IF NOT EXISTS refresh_tokens_user_id_idx
  ON refresh_tokens(user_id);

COMMIT;
