CREATE TABLE IF NOT EXISTS seller_ratings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seller_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  transaction_id INTEGER NOT NULL REFERENCES transactions(id) ON DELETE CASCADE,
  rated_by INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  rating NUMERIC NOT NULL,
  review TEXT,
  rated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  UNIQUE (transaction_id, rated_by)
);

CREATE INDEX IF NOT EXISTS seller_ratings_seller_id_idx ON seller_ratings(seller_id);
