DO $$
DECLARE
  rec RECORD;
BEGIN
  FOR rec IN
    SELECT table_name
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND column_name = 'id'
      AND is_identity = 'NO'
  LOOP
    EXECUTE format(
      'ALTER TABLE %I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY',
      rec.table_name
    );
  END LOOP;
END $$;
