CREATE TABLE IF NOT EXISTS contracts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bid_id INTEGER NOT NULL REFERENCES bids(id) ON DELETE CASCADE,
  property_id INTEGER NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  buyer_id INTEGER NOT NULL REFERENCES users(id),
  seller_id INTEGER NOT NULL REFERENCES users(id),
  transaction_id INTEGER REFERENCES transactions(id) ON DELETE SET NULL,
  contract_text TEXT NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  UNIQUE (bid_id)
);

CREATE INDEX IF NOT EXISTS contracts_property_id_idx ON contracts(property_id);
