-- Backfill schema pieces required by the current Grande Realtors backend.
-- Safe to run on a partially initialized database because all operations are idempotent.

BEGIN;

INSERT INTO roles (name) VALUES ('user'), ('buyer'), ('seller'), ('agent'), ('admin')
ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id VARCHAR(255) UNIQUE,
  firstname VARCHAR(100) NOT NULL,
  lastname VARCHAR(100) NOT NULL,
  number VARCHAR(20),
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role_id INTEGER REFERENCES roles(id),
  citizenship_front VARCHAR(255),
  citizenship_back VARCHAR(255),
  approval_status VARCHAR(50) DEFAULT 'approved',
  approval_reason TEXT,
  approved_at TIMESTAMP WITHOUT TIME ZONE,
  rejected_at TIMESTAMP WITHOUT TIME ZONE,
  reviewed_by INTEGER REFERENCES users(id),
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS public_id VARCHAR(255),
  ADD COLUMN IF NOT EXISTS citizenship_front VARCHAR(255),
  ADD COLUMN IF NOT EXISTS citizenship_back VARCHAR(255),
  ADD COLUMN IF NOT EXISTS approval_status VARCHAR(50) DEFAULT 'approved',
  ADD COLUMN IF NOT EXISTS approval_reason TEXT,
  ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP WITHOUT TIME ZONE,
  ADD COLUMN IF NOT EXISTS rejected_at TIMESTAMP WITHOUT TIME ZONE,
  ADD COLUMN IF NOT EXISTS reviewed_by INTEGER REFERENCES users(id),
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();

ALTER TABLE users
  ALTER COLUMN approval_status SET DEFAULT 'approved';

UPDATE users
SET approval_status = COALESCE(approval_status, 'approved')
WHERE approval_status IS NULL;

ALTER TABLE properties
  ADD COLUMN IF NOT EXISTS listing_purpose VARCHAR(50) DEFAULT 'sale',
  ADD COLUMN IF NOT EXISTS listing_type VARCHAR(50),
  ADD COLUMN IF NOT EXISTS sale_status VARCHAR(50) DEFAULT 'available',
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();

UPDATE properties
SET listing_purpose = COALESCE(listing_purpose, 'sale'),
    sale_status = COALESCE(sale_status, 'available')
WHERE listing_purpose IS NULL
   OR sale_status IS NULL;

CREATE TABLE IF NOT EXISTS transactions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id INTEGER NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  buyer_id INTEGER NOT NULL REFERENCES users(id),
  seller_id INTEGER NOT NULL REFERENCES users(id),
  amount NUMERIC NOT NULL,
  payment_method VARCHAR(50),
  transaction_date TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS bid_tickets (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auction_id INTEGER NOT NULL REFERENCES auctions(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  transaction_uuid VARCHAR(120) NOT NULL UNIQUE,
  transaction_code VARCHAR(120),
  amount NUMERIC NOT NULL,
  status VARCHAR(20) DEFAULT 'pending',
  paid_at TIMESTAMP WITHOUT TIME ZONE,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  UNIQUE (auction_id, user_id)
);

CREATE TABLE IF NOT EXISTS contracts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bid_id INTEGER NOT NULL REFERENCES bids(id) ON DELETE CASCADE,
  property_id INTEGER NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  buyer_id INTEGER NOT NULL REFERENCES users(id),
  seller_id INTEGER NOT NULL REFERENCES users(id),
  transaction_id INTEGER REFERENCES transactions(id) ON DELETE SET NULL,
  contract_text TEXT NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  UNIQUE (bid_id)
);

CREATE INDEX IF NOT EXISTS contracts_property_id_idx ON contracts(property_id);

CREATE TABLE IF NOT EXISTS seller_ratings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seller_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  transaction_id INTEGER NOT NULL REFERENCES transactions(id) ON DELETE CASCADE,
  rated_by INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  rating NUMERIC NOT NULL,
  review TEXT,
  rated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  UNIQUE (transaction_id, rated_by)
);

CREATE INDEX IF NOT EXISTS seller_ratings_seller_id_idx ON seller_ratings(seller_id);

CREATE TABLE IF NOT EXISTS messages (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id INTEGER NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  sender_id INTEGER NOT NULL REFERENCES users(id),
  receiver_id INTEGER NOT NULL REFERENCES users(id),
  body TEXT NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  read_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE INDEX IF NOT EXISTS messages_property_id_idx ON messages(property_id);
CREATE INDEX IF NOT EXISTS messages_receiver_id_idx ON messages(receiver_id);

CREATE TABLE IF NOT EXISTS password_resets (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash VARCHAR(255) NOT NULL,
  expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  used_at TIMESTAMP WITHOUT TIME ZONE,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS password_resets_token_hash_idx
  ON password_resets (token_hash);

CREATE INDEX IF NOT EXISTS password_resets_user_id_idx
  ON password_resets (user_id);

COMMIT;
