ALTER TABLE transactions
  ADD COLUMN IF NOT EXISTS handler_id INTEGER REFERENCES users(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS ratings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  buyer_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  rated_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  property_id INTEGER NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  transaction_id INTEGER NOT NULL REFERENCES transactions(id) ON DELETE CASCADE,
  role_type VARCHAR(20) NOT NULL CHECK (role_type IN ('seller', 'handler')),
  stars INTEGER NOT NULL CHECK (stars BETWEEN 1 AND 5),
  review TEXT,
  is_hidden BOOLEAN NOT NULL DEFAULT FALSE,
  moderated_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  moderated_at TIMESTAMP WITHOUT TIME ZONE,
  moderation_reason TEXT,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  UNIQUE (transaction_id, buyer_id, role_type)
);

CREATE INDEX IF NOT EXISTS ratings_rated_user_role_idx
  ON ratings(rated_user_id, role_type);

CREATE INDEX IF NOT EXISTS ratings_transaction_idx
  ON ratings(transaction_id);
